export {
  initiateDeviceCodeAuth,
  pollForAccessToken,
  completeOAuthFlow,
  getOrCreateToken,
  getCachedToken,
  saveToken,
  clearCachedToken,
  clearAllCachedTokens,
  needsRefresh,
  getCopilotHeaders,
  detectRequestType,
  createCopilotFetch,
  getApiBaseUrl,
  type CopilotAuthConfig,
  type CopilotAuthResult,
  type CopilotTokenInfo,
  type DeviceCodeResponse,
  type TokenCache,
} from "./copilot-auth"
